import React from "react";
import Head from "next/head";
import SEOItem from "../comps/items/common/SEOItem";
import Button from "../comps/items/buttons/Button";
import TextField from "../comps/items/inputs/TextField";
import Select from "../comps/items/inputs/Select";

import Footer001 from "../comps/sections/footers/Footer001";
import Navbar from "../comps/sections/navbars/Navbar";

import "swiper/css";
import "swiper/css/pagination";

import PhoneIcon from "../../assets/phone.svg";
import HeaderSection from "../comps/sections/headers/HeaderSection";
import ServiceSection from "../comps/sections/services/ServiceSection";
import StatsSection from "../comps/sections/stats/StatsSection";
import PricingSection from "../comps/sections/pricings/PricingSection";
import PreviewSection from "../comps/sections/previews/PreviewSection";

const Home = (): JSX.Element => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <SEOItem />

    <Navbar
      active="/"
      data={{
        logo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
        links: [
          {title: "Home", link: "/"},
          {title: "Rénovation", link: "/link-2"},
          {title: "Dépannage", link: "/link-2"},
          {title: "Le groupe 24/7 HESTIA", link: "/link-2"},
          {title: "Tarifs", link: "/link-2"},
        ],
        rightLinks: [
          {title: "01 83 64 12 15", link: "tel:01 83 64 12 15"},
        ],
      }}
    />

    <main>

      <HeaderSection
        data={{
          layout: "hs002",
          title: "Hello",
          subtitle: "Lorem ipsum",
          links: [
            {title: "Go to me", link: "/me"},
          ],
          slides: [
            {
              photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
              videoLink: "https://www.youtube.com/embed/nP4PRM7SRZE?autoplay=1&disablekb=1&loop=1&mute=1",
            },
          ],
        }}
      />

      <ServiceSection
        data={{
          layout: "ss003",
          title: "Service section",
          subtitle: "Lorem ipsum",
          background: "gray",
          services: [
            {
              name: "Service 1",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo neque id cursus consequat. Nam aliquam odio in est viverra euismod. Aliquam in massa at enim luctus ultrices in vel libero. Aliquam ultrices nisl sed efficitur pellentesque.",
              photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
              link: "/service-1",
            },
            {
              name: "Service 2",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo neque id cursus consequat. Nam aliquam odio in est viverra euismod. Aliquam in massa at enim luctus ultrices in vel libero. Aliquam ultrices nisl sed efficitur pellentesque.",
              photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
              link: "/service-2",
            },
            {
              name: "Service 1",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo neque id cursus consequat. Nam aliquam odio in est viverra euismod. Aliquam in massa at enim luctus ultrices in vel libero. Aliquam ultrices nisl sed efficitur pellentesque.",
              photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
              link: "/service-1",
            },
            {
              name: "Service 2",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo neque id cursus consequat. Nam aliquam odio in est viverra euismod. Aliquam in massa at enim luctus ultrices in vel libero. Aliquam ultrices nisl sed efficitur pellentesque.",
              photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
              link: "/service-2",
            },
          ],
          links: [
            {title: "Link 1", link: "/link-1"},
            {title: "Link 2", link: "/link-2"},
          ],
        }}
      />

      <StatsSection
        data={{
          layout: "sts001",
          title: "Stats section",
          subtitle: "Lorem ipsum",
          stats: [
            {label: "Label 1", value: "10"},
            {label: "Label 2", value: "10"},
            {label: "Label 3", value: "10"},
            {label: "Label 4", value: "10"},
          ],
          links: [
            {title: "Link 1", link: "/link-1"},
            {title: "Link 2", link: "/link-2"},
          ],
        }}
      />

      <PricingSection
        data={{
          layout: "ps001",
          title: "Pricing section",
          subtitle: "Lorem ipsum",
          background: "gray",
          links: [
            {title: "Link 1", link: "/link-1"},
            {title: "Link 2", link: "/link-2"},
          ],
          plans: [
            {
              title: "Plan 1",
              price: "300",
              unit: "euros",
              plan: "Lorem ipsum\nLorem ipsum\nLorem ipsum\nLorem ipsum",
              link: "/plan-1",
              linkTitle: "Order me",
            },
            {
              title: "Plan 1",
              price: "300",
              unit: "euros",
              plan: "Lorem ipsum\nLorem ipsum\nLorem ipsum\nLorem ipsum",
              recommended: "Best seller",
              link: "/plan-1",
              linkTitle: "Order me",
            },
            {
              title: "Plan 1",
              price: "300",
              unit: "euros",
              plan: "Lorem ipsum\nLorem ipsum\nLorem ipsum\nLorem ipsum",
              link: "/plan-1",
              linkTitle: "Order me",
            },
            {
              title: "Plan 1",
              price: "300",
              unit: "euros",
              plan: "Lorem ipsum\nLorem ipsum\nLorem ipsum\nLorem ipsum",
              link: "/plan-1",
              linkTitle: "Order me",
            },
          ],
        }}
      />

      <PreviewSection
        data={{
          layout: "prs001",
          title: "Preview section",
          subtitle: "Lorem ipsum",
          links: [
            {title: "Link 1", link: "/link-1"},
            {title: "Link 2", link: "/link-2"},
          ],
          document: {data: {attributes: {url: "https://cms.hestiaecobat.fr/uploads/sample_b76d581c36.pdf"}}},
        }}
      />

      <div className="container mx-auto space-y-8 py-16">
        <div className="space-y-4">
          <Button
            className="w-full"
            label="Click me"
            type="outlined"
          />

          <Button
            link
            className="w-full"
            label="Click me"
            href="/test"
            type="outlined"
          />
        </div>

        <div className="space-x-4">
          <Button
            label="Click me"
            type="outlined"
          />

          <Button
            link
            label="Click me"
            href="/test"
            type="outlined"
          />
        </div>

        <div className="space-y-4">
          <TextField
            label="Field name"
            placeholder="Name"
            type="date"
            lefticon={<PhoneIcon className="fill-current" />}
            righticon={<PhoneIcon className="fill-current" />}
          />

          <TextField
            color="secondary"
            label="Field name"
            type="time"
            placeholder="Phone"
            lefticon={<PhoneIcon className="fill-current" />}
            righticon={<PhoneIcon className="fill-current" />}
          />

          <Select
            label="Service"
            size="medium"
            color="primary"
            placeholder="Service"
            options={[
              {value: "A", label: "A"},
              {value: "b", label: "b"},
              {value: "C", label: "C"},
              {value: "D", label: "D"},
            ]}
          />

          <Select
            label="Test"
            size="medium"
            color="secondary"
            options={[
              {value: "A", label: "A"},
              {value: "b", label: "b"},
              {value: "C", label: "C"},
              {value: "D", label: "D"},
            ]}
          />
        </div>
      </div>
    </main>

    <Footer001
      data={{
        logo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
        photo: {data: {attributes: {url: "https://images.unsplash.com/photo-1516876902004-79f4bd1cb0dc"}}},
        links: [
          {title: "Home", link: "/link-1"},
          {title: "Rénovation", link: "/link-2"},
          {title: "Dépannage", link: "/link-2"},
          {title: "Le groupe 24/7 HESTIA", link: "/link-2"},
          {title: "Tarifs", link: "/link-2"},
        ],
        addresses: [
          {title: "Siège social", address: "103 boulevard Mad donald 75019 PARIS"},
          {title: "Pole Administratif", address: "1 rue Marceau 93100 MONTREUIL"},
        ],
        contacts: [
          {name: "PARIS/IDF", phone: "01 83 64 12 15", email: "contact@hestiaecobat.com"},
        ],
        socialLinks: {
          facebook: "https://facebook.com",
          linkedin: "https://linkedin.com",
          twitter: "https://twitter.com",
          youtube: "https://youtube.com",
          instagram: "https://instagram.com",
        },
        copyright: "© 2022 Hestia Eco Bat. All rights reserved.",
      }}
    />
  </div>
);

export default Home;
