import React from "react";
import Head from "next/head";
import SEOItem from "../components/items/common/SEOItem";

const Home = (): JSX.Element => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <SEOItem />

    <main className="container">
      <h1>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p>
        Get started by editing{" "}
      </p>
    </main>
  </div>
);

export default Home;
